### ISSUE TITLE
Dockerfile steps prevent using secret

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Broadsea-Atlasdb#3]
Hi @leeevans,

In this section here: https://github.com/OHDSI/Broadsea-Atlasdb/blob/main/Dockerfile#L161-L167, it looks like we execute the init of the postgres instance with all scripts and then try to pass along just the /data to a fresh postgres image.

This approach works when using POSTGRES_PASSWORD, but prevents us from using POSTGRES_PASSWORD_FILE (docker secret), as the secret file mount isn't available at this stage. The secret file mount isn't available until the entrypoint is run for the service.

Could we remove this section, or perhaps add a different cleanup command?

**Comment by leeevans** [comment]
@alondhe I believe you addressed this issue with commit 88d6de7.
