### ISSUE TITLE
Extend to allow the docker image to be used to populate an existing empty database for an external server

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [OHDSI/Broadsea-Atlasdb#9]
At present this creates a docker image that is used to provision postgresql in its entirety, but we (and I suspect others) are using managed postgresql database instances which makes it easier for our support model. It would be nice to use the same build process to populate an existing empty database on such instances.

I believe that we could change the existing docker image relatively easily to add a step between where it prepares the initial sql files and where it actually populates the database to give us the base, we can then tag this target and build a second docker image. This could then be called manually with relevant command line arguments to update the postgresql instance we want to target, or could be included as an init container

**Comment by leeevans** [comment]
@qcaas-nhs-sjt I would suggest connecting a SQL client to the postgres database running inside the docker container and using the postgres export command to export the database schemas (and optionally the data) to csv files which can be imported into an empty managed postgres database.
